name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install
        run: bun install

      - name: Build
        run: bun tsc

      - name: Run frontend tests
        run: bun cypress run --component --browser chrome

      - if: github.event_name == 'push'
        name: Update Database Schema
        run: bun drizzle-kit push
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
