name: Test

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Component Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build
        run: bun tsc

      - name: Cypress run
        run: bun cypress run --component --browser chrome
#      - name: Setup Expo
#        uses: expo/expo-github-action@v7
#        with:
#          expo-version: latest
#          eas-version: latest
#          token: ${{ secrets.EXPO_TOKEN }}
#
#      - name: Publish update
#        run: eas update --auto
