name: Test

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Component Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-bun@v1

      - name: Install
        run: bun install

      - name: Cypress run
        run: bunx cypress run --component --browser chrome
        env:
          NODE_ENV: production
