name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-apply.yml'

defaults:
  run:
    working-directory: terraform

jobs:
  terraform:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create State Bucket
        run: |
          if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null
          then
            echo "Bucket exists: $BUCKET_NAME"
          else
            echo "Bucket does not exist, creating: ${BUCKET_NAME}"
            aws s3 mb s3://"${BUCKET_NAME}"
          fi
        env:
          BUCKET_NAME: last-dram-terraform-us-east-2

      - name: Setup
        uses: hashicorp/setup-terraform@v1

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve
