#name: Expo Update
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  update:
#    name: EAS Update
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: .nvmrc
#
#      - name: Setup Expo
#        uses: expo/expo-github-action@v7
#        with:
#          expo-version: latest
#          eas-version: latest
#          token: ${{ secrets.EXPO_TOKEN }}
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Publish update
#        run: eas update --auto
